### ISSUE TITLE
Portrait crash

### ISSUE THREAD

**Issue by pralabhjain** [Tetr4/ZXingFragment#1]
When activity been launched in portrait mode it gives following crash

08-15 22:19:05.523: E/AndroidRuntime(17902): FATAL EXCEPTION: AsyncTask #2
08-15 22:19:05.523: E/AndroidRuntime(17902): Process: de.klimek.zxingfragment, PID: 17902
08-15 22:19:05.523: E/AndroidRuntime(17902): java.lang.RuntimeException: An error occured while executing doInBackground()
08-15 22:19:05.523: E/AndroidRuntime(17902):    at android.os.AsyncTask$3.done(AsyncTask.java:300)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at java.lang.Thread.run(Thread.java:818)
08-15 22:19:05.523: E/AndroidRuntime(17902): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=7372800; index=-1040570
08-15 22:19:05.523: E/AndroidRuntime(17902):    at de.klimek.zxingfragment.DecodeTask.swap(DecodeTask.java:118)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at de.klimek.zxingfragment.DecodeTask.rotate90(DecodeTask.java:113)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at de.klimek.zxingfragment.DecodeTask.buildLuminanceSource(DecodeTask.java:71)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at de.klimek.zxingfragment.DecodeTask.getResult(DecodeTask.java:48)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at de.klimek.zxingfragment.DecodeTask.doInBackground(DecodeTask.java:29)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at de.klimek.zxingfragment.DecodeTask.doInBackground(DecodeTask.java:1)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-15 22:19:05.523: E/AndroidRuntime(17902):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-15 22:19:05.523: E/AndroidRuntime(17902):    ... 4 more

**Comment by Tetr4** [comment]
I hope this fixed it :) The android camera api is deprecated now and the zxing version is rather old, because I have not worked on this repo for quite some time. But i added a branch for AndroidStudio Migration which you can take a look at.

**Comment by pralabhjain** [comment]
Thanks. Will look it.
